// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dend2hier
List dend2hier(List x, NumericVector height, CharacterVector newNames);
RcppExport SEXP hit_dend2hier(SEXP xSEXP, SEXP heightSEXP, SEXP newNamesSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type height(heightSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type newNames(newNamesSEXP);
    __result = Rcpp::wrap(dend2hier(x, height, newNames));
    return __result;
END_RCPP
}
// names
CharacterVector names(List x);
RcppExport SEXP hit_names(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type x(xSEXP);
    __result = Rcpp::wrap(names(x));
    return __result;
END_RCPP
}
