# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dend2hier <- function(x, height, newNames) {
    .Call('hit_dend2hier', PACKAGE = 'hit', x, height, newNames)
}

